### ISSUE TITLE
jsurvival-Survival module of clinicoPath for Jamovi ver 0.0.2

### ISSUE THREAD

**Issue by HanaLeeSNU** [sbalci/jsurvival#4]
Jamovi ver 2.3.28
jsurvival-Survival module of clinicoPath for Jamovi ver 0.0.2
Window

Hi. My name is Hana Lee.

Thank you for this amazing software. I conducted a multivariable survival analysis (ClinicoPath Survival package) and generated an adjusted survival curve. However, I encountered an issue where the plot end time has a default value of 60, and even though I try to increase it to 100, the plot does not change. Could this be a bug? Additionally, when I click the 95% CI and Risk table tabs, the plot does not update accordingly. Could you please advise on how to resolve these issues?

I look forward to your help.

**Comment by sbalci** [comment]
Dear @HanaLeeSNU 
Thank you for using jamovi and the modules. 
In multivariable survival analysis function, the adjusted curve part was problematic and I had to disable it in the recent versions. I will work on and try to reimplement it, but I am not sure if it will work.

**Comment by HanaLeeSNU** [comment]
Thank you for your response. I look forward to seeing this part corrected. I support your work and wish you success.

**Comment by sbalci** [comment]
worked on this and made a new release. https://github.com/sbalci/jsurvival/releases/tag/v0.0.2.48
But the adjusted curve analysis is still smae. the functions for adjusted curve do not have options for further changes.
I will work on other features and try to rebuild the functions myself.
